import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type Poziom = "Podstawy" | "Modele" | "Trening" | "Praktyka";
type Tutorial = { id: string; numer: string; tytul: string; opis: string; poziom: Poziom; czas: string; kod: string; kroki: string[] };

const tutoriale: Tutorial[] = [
  ["instalacja", "Instalacja i start", "Zainstaluj TotaAI oraz sprawdź wersję.", "Podstawy", "3 min", `python -m pip install --upgrade totaai\npython -c "import totaai; print(totaai.__version__)"`, ["Użyj python -m pip, aby paczka trafiła do właściwego interpretera.", "W projekcie najlepiej użyć osobnego środowiska .venv.", "Import totaai as ta jest używany we wszystkich przykładach."]],
  ["tensor", "Pierwszy Tensor", "Utwórz tensor i sprawdź jego dane oraz kształt.", "Podstawy", "4 min", `import totaai as ta\n\nx = ta.Tensor([[1, 2], [3, 4]])\nprint(x.dane)\nprint(x.ksztalt)  # (2, 2)`, ["Tensor przechowuje dane w formacie float32 NumPy.", "dane udostępnia wartości, a ksztalt opisuje ich wymiary.", "Tensor można przekazać bezpośrednio do modelu."]],
  ["operacje", "Operacje na Tensorach", "Łącz dodawanie, odejmowanie i mnożenie elementów.", "Podstawy", "5 min", `import totaai as ta\n\na = ta.Tensor([1, 2, 3])\nb = ta.Tensor([4, 5, 6])\nprint((a + b).dane)\nprint((a * b).dane)\nprint((b - a).dane)`, ["Operatory +, - i * działają element po elemencie.", "Możesz łączyć tensory z liczbami, np. a * 0.5.", "TotaAI śledzi te operacje, jeśli tensor wymaga gradientu."]],
  ["macierze", "Mnożenie macierzy", "Użyj operatora @ do łączenia wejść z wagami.", "Podstawy", "5 min", `import totaai as ta\n\nwejscie = ta.Tensor([[1, 2]])\nwagi = ta.Tensor([[0.2, 0.4], [0.1, 0.3]])\nwynik = wejscie @ wagi\nprint(wynik.dane)`, ["Operator @ wykonuje mnożenie macierzowe.", "To podstawowa operacja warstwy liniowej.", "Wymiary wewnętrzne macierzy muszą być zgodne."]],
  ["gradient", "Automatyczne gradienty", "Policz pochodną bez ręcznej matematyki.", "Podstawy", "6 min", `import totaai as ta\n\nx = ta.Tensor([2.0], wymaga_gradientu=True)\ny = x * x + 3\ny.wstecz()\nprint(x.gradient)  # [4.]`, ["Ustaw wymaga_gradientu=True dla zmiennej, względem której liczysz pochodną.", "wstecz() rozpoczyna propagację gradientu od wyniku.", "Dla y = x*x + 3 pochodna wynosi 2*x."]],
  ["redukcje", "Suma i średnia", "Zamień wiele wartości na jedną funkcją celu.", "Podstawy", "4 min", `import totaai as ta\n\nx = ta.Tensor([1, 2, 3], wymaga_gradientu=True)\nstrata = x.srednia()\nstrata.wstecz()\nprint(strata.dane)\nprint(x.gradient)`, ["suma() i srednia() redukują elementy tensora.", "Średnia jest podstawą funkcji MSE.", "Po wstecz() gradient każdego elementu średniej wynosi 1/n."]],
  ["liniowa", "Warstwa liniowa", "Stwórz pierwszą trenowalną warstwę.", "Modele", "5 min", `import totaai as ta\n\nwarstwa = ta.WarstwaLiniowa(2, 3)\nwynik = warstwa(ta.Tensor([[0.5, 1.0]]))\nprint(wynik.dane)\nprint(warstwa.wagi.ksztalt)`, ["Pierwszy argument to liczba cech wejściowych.", "Drugi argument to liczba neuronów wyjściowych.", "Warstwa zawiera trenowalne wagi i bias."]],
  ["relu", "Aktywacja ReLU", "Dodaj nieliniowość do ukrytej warstwy.", "Modele", "4 min", `import totaai as ta\n\nx = ta.Tensor([[-2, 0, 3]])\nprint(ta.ReLU()(x).dane)  # [[0, 0, 3]]`, ["ReLU zwraca zero dla wartości ujemnych.", "Najczęściej umieszcza się ją między warstwami liniowymi.", "Jest prostą, domyślną aktywacją warstw ukrytych."]],
  ["sigmoid", "Aktywacja Sigmoid", "Zamień wynik na wartość z zakresu od 0 do 1.", "Modele", "4 min", `import totaai as ta\n\nwynik = ta.Sigmoid()(ta.Tensor([[-2, 0, 2]]))\nprint(wynik.dane)`, ["Sigmoid jest użyteczny przy klasyfikacji binarnej.", "Wyniki bliskie 1 oznaczają wysokie prawdopodobieństwo klasy pozytywnej.", "Wyniki bliskie 0 oznaczają klasę negatywną."]],
  ["softmax", "Aktywacja Softmax", "Zamień trzy logity na rozkład klas.", "Modele", "4 min", `import totaai as ta\n\nprob = ta.Softmax()(ta.Tensor([[1.0, 2.0, 0.5]]))\nprint(prob.dane)\nprint(prob.dane.sum(axis=-1))`, ["Softmax normalizuje ostatni wymiar do sumy 1.", "Każde wyjście reprezentuje prawdopodobieństwo klasy.", "Największą klasę wybierzesz przez argmax(axis=-1)."]],
  ["mse", "Strata MSE", "Policz błąd prognozy regresyjnej.", "Modele", "4 min", `import totaai as ta\n\nprzewidywane = ta.Tensor([[2.0], [3.0]])\noczekiwane = ta.Tensor([[1.0], [4.0]])\nprint(ta.MSE()(przewidywane, oczekiwane).dane)`, ["MSE to średnia z kwadratów różnic.", "Używaj jej dla wartości liczbowych, np. ceny lub temperatury.", "W treningu strata wskazuje optymalizatorowi kierunek zmiany wag."]],
  ["entropia", "Entropia krzyżowa", "Oblicz stratę klasyfikacji wieloklasowej.", "Modele", "5 min", `import totaai as ta\n\nlogity = ta.Tensor([[2.0, 0.5, 0.1]])\nklasy = ta.Tensor([0])\nstrata = ta.EntropiaKrzyzowa()(logity, klasy)\nprint(strata.dane)`, ["Do funkcji podaj logity oraz indeksy klas.", "Klasa 0 oznacza pierwszą kolumnę logitów.", "Nie dodawaj Softmax przed EntropiaKrzyzowa w prawdziwym treningu logitów."]],
  ["sgd", "Optymalizator SGD", "Zaktualizuj parametr prostym spadkiem gradientu.", "Trening", "5 min", `import totaai as ta\n\nw = ta.Tensor([1.0], wymaga_gradientu=True)\nstrata = (w - 4) * (w - 4)\nstrata.wstecz()\nta.SGD(tempo=0.1).krok([w])\nprint(w.dane)`, ["Najpierw oblicz gradient metodą wstecz().", "krok() aktualizuje parametry z gradientem.", "Mniejsze tempo daje ostrożniejsze zmiany wag."]],
  ["adam", "Optymalizator Adam", "Użyj adaptacyjnego optymalizatora w modelu.", "Trening", "4 min", `import totaai as ta\n\noptymalizator = ta.Adam(\n    tempo=0.001, beta1=0.9, beta2=0.999\n)`, ["Adam jest dobrym punktem startowym dla większości przykładów.", "tempo kontroluje skalę aktualizacji.", "beta1 i beta2 zwykle pozostaw na wartościach domyślnych."]],
  ["xor", "Projekt: XOR", "Wytrenuj pełny model rozwiązujący problem XOR.", "Praktyka", "10 min", `import totaai as ta\n\nmodel = ta.Model().dodaj(\n    ta.WarstwaLiniowa(2, 8), ta.Sigmoid(),\n    ta.WarstwaLiniowa(8, 1), ta.Sigmoid(),\n)\nmodel.skompiluj(ta.MSE(), ta.Adam(tempo=0.05))\nmodel.trenuj([[0,0],[0,1],[1,0],[1,1]], [[0],[1],[1],[0]], epoki=500)`, ["XOR nie jest liniowo separowalny, więc potrzebuje warstwy ukrytej.", "Sigmoid na wyjściu ogranicza wynik do przedziału 0-1.", "Po treningu sprawdź model.przewidz([[1, 0]])."]],
  ["regresja", "Projekt: regresja", "Dopasuj model do zależności y = 2x + 1.", "Praktyka", "8 min", `import totaai as ta\n\nmodel = ta.Model().dodaj(ta.WarstwaLiniowa(1, 1))\nmodel.skompiluj(ta.MSE(), ta.Adam(tempo=0.05))\nmodel.trenuj([[0],[1],[2],[3]], [[1],[3],[5],[7]], epoki=200)\nprint(model.przewidz([[4]]).dane)`, ["Regresja nie wymaga aktywacji wyjściowej.", "Jedna warstwa liniowa może nauczyć się prostej prostej.", "MSE mierzy różnicę między przewidywaniem i celem."]],
  ["binarna", "Projekt: klasyfikacja binarna", "Rozpoznaj, czy liczba jest dodatnia.", "Praktyka", "8 min", `import totaai as ta\n\nmodel = ta.Model().dodaj(\n    ta.WarstwaLiniowa(1, 1), ta.Sigmoid()\n)\nmodel.skompiluj(ta.MSE(), ta.Adam(tempo=0.03))\nmodel.trenuj([[-2],[-1],[1],[2]], [[0],[0],[1],[1]], epoki=200)`, ["Sigmoid daje wynik interpretowany jako prawdopodobieństwo.", "Dla decyzji binarnej zastosuj próg 0.5.", "Dane i etykiety powinny mieć ten sam pierwszy wymiar."]],
  ["wieloklasowa", "Projekt: trzy klasy", "Zbuduj strukturę klasyfikatora wieloklasowego.", "Praktyka", "9 min", `import totaai as ta\n\nmodel = ta.Model().dodaj(\n    ta.WarstwaLiniowa(4, 16), ta.ReLU(),\n    ta.WarstwaLiniowa(16, 3)\n)\nmodel.skompiluj(ta.EntropiaKrzyzowa(), ta.Adam())\nmodel.trenuj(dane, klasy, epoki=50, rozmiar_partii=32)`, ["Warstwa wyjściowa ma trzy neurony, po jednym dla klasy.", "Przekaż indeksy klas 0, 1 i 2 do etykiet.", "Po predykcji użyj wynik.dane.argmax(axis=-1)."]],
  ["partie", "Trening partiami", "Podziel dane na małe porcje i mieszaj je na każdej epoce.", "Trening", "6 min", `historia = model.trenuj(\n    dane, etykiety, epoki=30,\n    rozmiar_partii=32, tasuj=True\n)\nprint(historia[-1])`, ["Partie ograniczają liczbę przykładów przetwarzanych w jednym kroku.", "tasuj=True zmienia kolejność danych między epokami.", "Zwrócona historia zawiera średnią stratę każdej epoki."]],
  ["walidacja", "Ocena walidacyjna", "Sprawdź stratę bez zmieniania wag modelu.", "Trening", "4 min", `blad = model.ocen(\n    dane_walidacyjne,\n    etykiety_walidacyjne,\n)\nprint(f"Blad: {blad:.4f}")`, ["Najpierw trenuj na zbiorze treningowym.", "ocen() wywołaj na danych, których model nie widział w treningu.", "Rosnący błąd walidacyjny może oznaczać przeuczenie."]],
  ["podsumowanie", "Podsumowanie modelu", "Sprawdź architekturę i liczbę parametrów.", "Trening", "3 min", `model = ta.Model().dodaj(\n    ta.WarstwaLiniowa(4, 8), ta.ReLU(),\n    ta.WarstwaLiniowa(8, 3),\n)\nmodel.podsumowanie()`, ["podsumowanie() wypisuje każdą warstwę modelu.", "Dla warstw liniowych liczy wagi i bias.", "Pomaga szybko sprawdzić rozmiar architektury."]],
  ["zapis", "Zapis modelu", "Zapisz wytrenowaną architekturę i jej wagi.", "Praktyka", "3 min", `model.zapisz("model.tota")\n\n# plik model.tota zachowaj razem z projektem`, ["Zapisuj model po zakończeniu treningu.", "Plik zawiera serializowany model i parametry.", "Przechowuj go wyłącznie w zaufanym miejscu."]],
  ["odczyt", "Odczyt modelu", "Odtwórz zapisany model w nowym programie.", "Praktyka", "3 min", `import totaai as ta\n\nmodel = ta.Model.wczytaj("model.tota")\nprint(model.przewidz([[1, 0]]).dane)`, ["wczytaj() jest metodą statyczną klasy Model.", "Po odczycie możesz natychmiast wykonać przewidywanie.", "Nie wczytuj nieznanych plików .tota."]],
  ["wlasna-warstwa", "Własna warstwa", "Napisz prostą warstwę dziedziczącą po Warstwa.", "Praktyka", "7 min", `import totaai as ta\n\nclass Podwoj(ta.Warstwa):\n    def przepusc(self, x):\n        return x * 2\n\nprint(Podwoj()(ta.Tensor([1, 2])).dane)`, ["Dziedzicz po ta.Warstwa.", "Zaimplementuj metodę przepusc(self, x).", "Dla parametrów trenowalnych nadpisz także parametry()."]],
  ["tanh", "Aktywacja Tanh", "Użyj aktywacji z zakresem od -1 do 1.", "Modele", "4 min", `import totaai as ta\n\nx = ta.Tensor([[-2, 0, 2]])\nprint(ta.Tanh()(x).dane)`, ["Tanh centruje wartości wokół zera.", "Użyj jej w warstwie ukrytej zamiast ReLU.", "Jej wartości należą do przedziału od -1 do 1."]],
  ["leaky-relu", "LeakyReLU", "Zachowaj gradient dla wartości ujemnych.", "Modele", "4 min", `import totaai as ta\n\naktywacja = ta.LeakyReLU(nachylenie=0.01)\nprint(aktywacja(ta.Tensor([[-2, 2]])).dane)`, ["LeakyReLU jest wariantem ReLU.", "Wartości ujemne są skalowane, nie zerowane.", "nachylenie kontroluje ich mały gradient."]],
  ["dropout", "Dropout", "Dodaj regularyzację wyłącznie podczas treningu.", "Modele", "6 min", `model.dodaj(\n    ta.WarstwaLiniowa(8, 16), ta.ReLU(),\n    ta.Dropout(0.2),\n    ta.WarstwaLiniowa(16, 1), ta.Sigmoid(),\n)`, ["Dropout wyłącza losowo 20% aktywacji w treningu.", "model.przewidz() automatycznie wyłącza Dropout.", "Użyj go między warstwami ukrytymi."]],
  ["bce", "Entropia binarna", "Trenuj klasyfikację 0/1 z Sigmoid i BCE.", "Praktyka", "7 min", `model = ta.Model().dodaj(\n    ta.WarstwaLiniowa(2, 1), ta.Sigmoid()\n)\nmodel.skompiluj(ta.EntropiaBinarna(), ta.Adam())\nmodel.trenuj(dane, etykiety, epoki=100)`, ["Wyjście Sigmoid daje prawdopodobieństwo klasy 1.", "Etykiety muszą mieć wartości 0 albo 1.", "EntropiaBinarna mierzy jakość prawdopodobieństw."]],
  ["podzial", "Podział danych", "Rozdziel dane na trening i test.", "Praktyka", "5 min", `x_tr, x_test, y_tr, y_test = ta.podziel_dane(\n    dane, etykiety, udzial_testowy=0.2, ziarno=42\n)\nmodel.trenuj(x_tr, y_tr, epoki=20)\nprint(model.ocen(x_test, y_test))`, ["20% danych trafi do zbioru testowego.", "ziarno zapewnia powtarzalny podział.", "Nie trenuj modelu na zbiorze testowym."]],
  ["metryki", "Metryki modelu", "Raportuj dokładność i błąd bezwzględny.", "Praktyka", "4 min", `wynik = model.przewidz(x_test)\nprint(ta.dokladnosc(wynik, y_test))\nprint(ta.blad_sredni_bezwzgledny(wynik, y_test))`, ["dokladnosc działa dla klasyfikacji binarnej i wieloklasowej.", "blad_sredni_bezwzgledny jest metryką regresyjną.", "Metryki używaj po treningu, do raportowania wyniku."]],
].map(([id, tytul, opis, poziom, czas, kod, kroki], index) => ({ id: id as string, tytul: tytul as string, opis: opis as string, poziom: poziom as Poziom, czas: czas as string, kod: kod as string, kroki: kroki as string[], numer: String(index + 1).padStart(2, "0") }));

const filtry: (Poziom | "Wszystkie")[] = ["Wszystkie", "Podstawy", "Modele", "Trening", "Praktyka"];

function KatalogTutoriali() {
  const zHash = () => tutoriale.find((item) => window.location.hash === `#tutorial/${item.id}`) ?? tutoriale[0];
  const [aktywny, ustawAktywny] = useState(zHash);
  const [filtr, ustawFiltr] = useState<Poziom | "Wszystkie">("Wszystkie");
  const [szukaj, ustawSzukaj] = useState("");
  useEffect(() => { const zmien = () => ustawAktywny(zHash()); window.addEventListener("hashchange", zmien); return () => window.removeEventListener("hashchange", zmien); }, []);
  const widoczne = tutoriale.filter((item) => (filtr === "Wszystkie" || item.poziom === filtr) && `${item.tytul} ${item.opis}`.toLowerCase().includes(szukaj.toLowerCase()));
  const wybierz = (item: Tutorial) => { window.location.hash = `tutorial/${item.id}`; ustawAktywny(item); document.querySelector("#lekcja")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  return <section className="academy" id="tutoriale"><header className="academy-head"><div><span className="eyebrow">BIBLIOTEKA NAUKI / 24 LEKCJE</span><h2>Nie czytaj o AI.<br /><em>Zbuduj je.</em></h2></div><p>Pełny program od pierwszego Tensora do zapisu własnego modelu. Każda lekcja ma osobny link, kod i checklistę.</p></header><div className="academy-controls"><input value={szukaj} onChange={(event) => ustawSzukaj(event.target.value)} placeholder="Szukaj tutorialu" aria-label="Szukaj tutorialu" /><div className="filters">{filtry.map((item) => <button className={filtr === item ? "selected" : ""} key={item} onClick={() => ustawFiltr(item)}>{item}</button>)}</div></div><div className="lesson-grid">{widoczne.map((item) => <button className="lesson-card" key={item.id} onClick={() => wybierz(item)}><span>{item.numer} <i>{item.poziom}</i></span><h3>{item.tytul}</h3><p>{item.opis}</p><small>{item.czas} <b>Otwórz →</b></small></button>)}</div><article className="lesson" id="lekcja"><aside><span>OTWARTA LEKCJA</span><b>{aktywny.numer}</b><p>{aktywny.poziom} · {aktywny.czas}</p><a href={`#tutorial/${aktywny.id}`}>#tutorial/{aktywny.id}</a></aside><div className="lesson-body"><h3>{aktywny.tytul}</h3><p className="lesson-intro">{aktywny.opis}</p><pre><code>{aktywny.kod}</code></pre><div className="steps"><h4>Plan działania</h4>{aktywny.kroki.map((krok, index) => <p key={krok}><b>{index + 1}</b>{krok}</p>)}</div></div></article></section>;
}

function App() {
  const [skopiowano, ustawSkopiowano] = useState(false);
  const kopiuj = async () => { await navigator.clipboard.writeText("python -m pip install --upgrade totaai"); ustawSkopiowano(true); window.setTimeout(() => ustawSkopiowano(false), 1800); };
  return <main><nav><a className="logo" href="#top"><span>◆</span>TotaAI</a><div className="links"><a href="#mozliwosci">Możliwości</a><a href="#tutoriale">Tutoriale</a><a href="https://github.com/totatomasz13-web/TotaAI">GitHub ↗</a></div></nav><section className="hero" id="top"><span className="eyebrow">POLSKI FRAMEWORK AI / v0.2.0</span><p className="hero-index">01—24 <i>lekcje od podstaw</i></p><h1>Ucz AI<br /><em>po polsku.</em></h1><p className="lead">TotaAI to mała, przejrzysta biblioteka i praktyczna ścieżka nauki. Bez żargonu. Bez czarnej skrzynki.</p><div className="actions"><a className="primary" href="#tutorial/instalacja">Rozpocznij kurs <span>→</span></a><button className="install" onClick={kopiuj}>{skopiowano ? "Skopiowano ✓" : "python -m pip install totaai"}</button></div></section><section className="signal"><div><b>24</b><span>tutoriale<br />z kodem</span></div><div><b>4</b><span>ścieżki<br />nauki</span></div><div><b>100%</b><span>polskie<br />API</span></div><p>Od Tensora do gotowego modelu. Każdy przykład korzysta wyłącznie z obecnie dostępnego API TotaAI.</p></section><section className="features" id="mozliwosci"><div className="section-title"><span>CO ZNAJDZIESZ W ŚRODKU</span><h2>Mały rdzeń.<br /><em>Duża jasność.</em></h2></div><div className="grid"><article><b>01</b><h3>Autodiff</h3><p>Śledź operacje i obliczaj gradienty bez ręcznej matematyki.</p></article><article><b>02</b><h3>Warstwy</h3><p>Buduj modele z WarstwaLiniowa, ReLU, Sigmoid i Softmax.</p></article><article><b>03</b><h3>Trening</h3><p>Użyj MSE, EntropiaKrzyzowa, SGD lub Adam oraz batchowania.</p></article><article><b>04</b><h3>Praktyka</h3><p>Zapisuj modele, oceniaj wynik i twórz własne warstwy.</p></article></div></section><KatalogTutoriali /><footer><div className="logo"><span>◆</span>TotaAI</div><p>AI, które mówi po Twojemu.</p><a href="https://github.com/totatomasz13-web/TotaAI">GitHub ↗</a></footer></main>;
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
