import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type Tutorial = { id: string; label: string; numer: string; title: string; intro: string; code: string; steps: string[] };

const tutoriale: Tutorial[] = [
  { id: "start", label: "Start", numer: "01", title: "Pierwszy model", intro: "Zbuduj, skompiluj i wytrenuj małą sieć neuronową na danych XOR.", code: `import totaai as ta\n\nmodel = ta.Model()\nmodel.dodaj(\n    ta.WarstwaLiniowa(2, 8),\n    ta.Sigmoid(),\n    ta.WarstwaLiniowa(8, 1),\n    ta.Sigmoid(),\n)\nmodel.skompiluj(ta.MSE(), ta.Adam(tempo=0.05))\n\ndane = ta.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]])\netykiety = ta.Tensor([[0], [1], [1], [0]])\nmodel.trenuj(dane, etykiety, epoki=500, pokazuj_postep=False)\nprint(model.przewidz([[1, 0]]).dane)`, steps: ["Zainstaluj bibliotekę poleceniem pip install totaai.", "WarstwaLiniowa tworzy połączenia między wejściem a neuronami ukrytymi.", "MSE mierzy błąd, a Adam aktualizuje wagi na podstawie gradientów.", "Wynik dla [1, 0] powinien być bliski 1."] },
  { id: "tensor", label: "Tensor i gradienty", numer: "02", title: "Zrozum autodiff", intro: "Zobacz, jak TotaAI śledzi operacje i oblicza pochodną bez ręcznego liczenia.", code: `import totaai as ta\n\nx = ta.Tensor([2.0], wymaga_gradientu=True)\ny = x * x + 3\ny.wstecz()\n\nprint(y.dane)       # [7.]\nprint(x.gradient)   # [4.]`, steps: ["wymaga_gradientu=True włącza śledzenie dla tensora.", "Operatory + i * budują graf obliczeń.", "wstecz() przechodzi graf od wyniku do jego rodziców.", "gradient zawiera pochodną wyniku względem x."] },
  { id: "klasyfikacja", label: "Klasyfikacja", numer: "03", title: "Klasyfikacja wieloklasowa", intro: "Zbuduj klasyfikator z Softmax i entropią krzyżową dla trzech klas.", code: `import totaai as ta\n\nmodel = ta.Model()\nmodel.dodaj(\n    ta.WarstwaLiniowa(4, 16),\n    ta.ReLU(),\n    ta.WarstwaLiniowa(16, 3),\n    ta.Softmax(),\n)\nmodel.skompiluj(ta.EntropiaKrzyzowa(), ta.Adam())\nmodel.trenuj(dane, klasy, epoki=50, rozmiar_partii=32)\n\nprawdopodobienstwa = model.przewidz(nowe_dane)\nklasa = prawdopodobienstwa.dane.argmax(axis=-1)`, steps: ["Ostatnia warstwa ma trzy wyjścia, po jednym na klasę.", "Softmax zamienia logity na prawdopodobieństwa sumujące się do 1.", "Etykiety przekazuj jako indeksy klas, np. [0, 2, 1].", "argmax wybiera klasę o najwyższym prawdopodobieństwie."] },
  { id: "partie", label: "Batchowanie", numer: "04", title: "Trening partiami", intro: "Trenuj większy zbiór danych w małych partiach i mierz wynik na walidacji.", code: `model.trenuj(\n    dane_treningowe,\n    etykiety_treningowe,\n    epoki=25,\n    rozmiar_partii=32,\n    tasuj=True,\n    pokazuj_postep=True,\n)\n\nblad = model.ocen(dane_walidacyjne, etykiety_walidacyjne)\nprint(f"Blad walidacji: {blad:.4f}")\nmodel.podsumowanie()`, steps: ["rozmiar_partii=32 ogranicza ilość danych w jednym kroku.", "tasuj=True zmienia kolejność przykładów na początku epoki.", "Historia zwracana przez trenuj zawiera średnią stratę każdej epoki.", "ocen() sprawdza stratę bez aktualizowania parametrów."] },
  { id: "zapis", label: "Zapis modelu", numer: "05", title: "Zapis i odczyt", intro: "Zachowaj wytrenowane wagi i użyj modelu później bez ponownego treningu.", code: `model.zapisz("model.tota")\n\n# W osobnym procesie\nimport totaai as ta\nodtworzony = ta.Model.wczytaj("model.tota")\nwynik = odtworzony.przewidz(dane_testowe)\nprint(wynik.dane)`, steps: ["zapisz() zapisuje architekturę, parametry i konfigurację modelu.", "wczytaj() odtwarza model z pliku.", "Format jest przeznaczony dla zaufanych plików lokalnych.", "Nie wczytuj plików modeli z nieznanego źródła."] },
];

function Dokumentacja() {
  const wybierz = () => tutoriale.find((tutorial) => window.location.hash === `#docs/${tutorial.id}`) ?? tutoriale[0];
  const [aktywny, ustawAktywny] = useState(wybierz);
  useEffect(() => { const zmien = () => ustawAktywny(wybierz()); window.addEventListener("hashchange", zmien); return () => window.removeEventListener("hashchange", zmien); });
  const przejdz = (tutorial: Tutorial) => { window.location.hash = `docs/${tutorial.id}`; ustawAktywny(tutorial); };
  return <section className="docs" id="dokumentacja"><div className="section-title"><span>02 / DOKUMENTACJA API</span><h2>Ucz się przez<br /><em>budowanie.</em></h2><p className="docs-intro">Każdy tutorial jest osobną zakładką. Kod możesz skopiować, uruchomić i rozwijać we własnym projekcie.</p></div><div className="docs-content"><div className="doc-tabs" role="tablist">{tutoriale.map((tutorial) => <button className={tutorial.id === aktywny.id ? "doc-tab active" : "doc-tab"} key={tutorial.id} onClick={() => przejdz(tutorial)} role="tab" aria-selected={tutorial.id === aktywny.id}><b>{tutorial.numer}</b>{tutorial.label}</button>)}</div><article className="tutorial"><div className="tutorial-heading"><span> TUTORIAL / {aktywny.numer}</span><h3>{aktywny.title}</h3><p>{aktywny.intro}</p></div><pre><code>{aktywny.code}</code></pre><div className="tutorial-steps"><h4>Jak to działa</h4>{aktywny.steps.map((step, index) => <p key={step}><b>{index + 1}</b>{step}</p>)}</div></article><a className="docs-link" href="https://github.com/totatomasz13-web/TotaAI/blob/main/docs/API.md">Pełna dokumentacja API na GitHubie ↗</a></div></section>;
}

function App() {
  const [skopiowano, ustawSkopiowano] = useState(false);
  const kopiuj = async () => { await navigator.clipboard.writeText("pip install totaai"); ustawSkopiowano(true); window.setTimeout(() => ustawSkopiowano(false), 1600); };
  return <main>
    <nav><a className="logo" href="#top"><span>◆</span> TotaAI</a><div className="links"><a href="#mozliwosci">Możliwości</a><a href="#dokumentacja">Dokumentacja</a><a className="github" href="https://github.com/totatomasz13-web/TotaAI">GitHub ↗</a></div></nav>
    <section className="hero" id="top"><div className="eyebrow">POLSKI FRAMEWORK AI · v0.2.0</div><h1>Buduj AI.<br /><em>Po swojemu.</em></h1><p className="lead">Czytelna biblioteka uczenia maszynowego z polskim API. Od pierwszego neuronu do własnego modelu, bez bariery terminologii.</p><div className="actions"><a className="primary" href="#docs/start">Zacznij tutorial <span>→</span></a><a className="hero-docs" href="#dokumentacja">Dokumentacja API ↗</a><button className="secondary copy" onClick={kopiuj}>{skopiowano ? "Skopiowano ✓" : "pip install totaai"}</button></div></section>
    <section className="code-card" id="start"><div className="dots"><i></i><i></i><i></i><small>przyklad.py</small></div><pre><code>{tutoriale[0].code}</code></pre></section>
    <section className="features" id="mozliwosci"><div className="section-title"><span>01 / DLACZEGO TOTA</span><h2>Mniej składni.<br /><em>Więcej pomysłów.</em></h2></div><div className="grid"><article><b>01</b><h3>Polskie API</h3><p>WarstwaLiniowa, trenuj, przewidz. Nazwy, które mówią co robią.</p></article><article><b>02</b><h3>Autodiff w środku</h3><p>Automatyczne gradienty i gotowe optymalizatory bez ręcznej matematyki.</p></article><article><b>03</b><h3>Gotowe do eksperymentów</h3><p>Batchowanie, walidacja, zapis modeli i czytelny wynik treningu.</p></article><article><b>04</b><h3>Otwarty rozwój</h3><p>MIT, testy i dokumentacja. Twórz własne warstwy oraz architektury.</p></article></div></section>
    <Dokumentacja />
    <footer><div className="logo"><span>◆</span> TotaAI</div><p>AI, które mówi po Twojemu.</p><a href="https://github.com/totatomasz13-web/TotaAI">github.com/totatomasz13-web/TotaAI ↗</a></footer>
  </main>;
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
